export const typeAbbrMap = {
"LANDSCAPING" : "LDS",
"FIRE EXTINGUISHER MAINT" : "FEM",
"FIRE INSPECTION": "FINP",
"EXTERMINATOR SERVICE": "ETS",
"GENERATOR PM": "GEN",
"HVAC PM": "HVC",
"GENERATOR REPAIR": "GERP",
"HVAC REPAIR": "HVRP",
"GENERATOR FUEL": "GNFL",
"TRANSFER SWITCH REPAIR": "TSRP",
"TOWER MINOR MAINTENANCE": "TWR",
"SNOW REMOVAL PM": "SNW",
"BATTERY PM": "BATT"
}