export const getProjects = `query($latitude: String!,$longitude: String!,$proximity: String!,$user_id: String!){
                            getProjects(latitude:$latitude,longitude:$longitude,proximity:$proximity,user_id:$user_id){
                                projects{
                                    siteid
                                    fuze_site_id
                                    fuze_sitetype
                                    sitetype
                                    ps_loc_code
                                    site_unid
                                    sitename
                                    switch_name
                                    switch_unid
                                    market
                                    sub_market
                                    proj_number
                                    project_name
                                    project_type
                                    project_status
                                    vendor
                                    distance
                                    distance_text
                                    address
                                    city
                                    state
                                    county
                                    zip
                                    latitude
                                    longitude
                                    nodes{
                                        gnodeb_id
                                        gnodeb_name
                                        du_id
                                        du_name
                                        azimuth
                                        sector_id
                                        downtilt
                                    }
                                    equipmentList{
                                        equipmentId
                                        payload
                                        gnodebid
                                        du_id
                                        sector_id
                                    }
                                }
                            }     
                        }`